---
name: my-test-deployment

releases:
- {name: redis, version: 12}

jobs:
- name: redis-master
  instances: 1
  templates:
  - {name: redis-server, release: redis}
  persistent_disk: 10_240
  resource_pool: redis-servers
  networks:
  - name: default

properties:
  redis:
    max_connections: 10
